@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":EditStudentCommandParser" as EditStudentCommandParser LOGIC_COLOR
participant "c:EditStudentCommand" as EditStudentCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("edit_s 1 <fields>")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("edit_s 1 <fields>")
activate AddressBookParser

create EditStudentCommandParser
AddressBookParser -> EditStudentCommandParser
activate EditStudentCommandParser

EditStudentCommandParser --> AddressBookParser
deactivate EditStudentCommandParser

AddressBookParser -> EditStudentCommandParser : parse("1 <fields>")
activate EditStudentCommandParser

create EditStudentCommand
EditStudentCommandParser -> EditStudentCommand
activate EditStudentCommand

EditStudentCommand --> EditStudentCommandParser :
deactivate EditStudentCommand

EditStudentCommandParser --> AddressBookParser : c
deactivate EditStudentCommandParser
'Hidden arrow to position the destroy marker below the activation bar.
EditStudentCommandParser -[hidden]-> AddressBookParser
destroy EditStudentCommandParser

AddressBookParser --> LogicManager : c
deactivate AddressBookParser

LogicManager -> EditStudentCommand : execute(m)
activate EditStudentCommand

EditStudentCommand -> Model : getFilteredPersonList()
activate Model
Model --> EditStudentCommand
deactivate Model

EditStudentCommand -> Model : setPerson(personToEdit, editedPerson)
activate Model
Model --> EditStudentCommand
deactivate Model

EditStudentCommand -> Model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model
Model --> EditStudentCommand
deactivate Model

create CommandResult
EditStudentCommand -> CommandResult
activate CommandResult
CommandResult --> EditStudentCommand
deactivate CommandResult

EditStudentCommand --> LogicManager : r
deactivate EditStudentCommand

[<-- LogicManager
deactivate LogicManager
@enduml
